# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "api-rust"
version = "0.1.0"
edition = "2024"

# https://www.cargo-lambda.info/commands/deploy.html
[package.metadata.lambda.deploy]
memory = 128
timeout = 10

[[bin]]
name = "api-rust"
path = "src/main.rs"

[features]
default = []
lambda = ["dep:lambda_http", "dep:poem-lambda"]
testing = []

[dependencies]
argon2 = "0.5.3"
async-trait = "0.1.83"
jsonwebtoken = "9.3.1"
lambda_http = { version = "0.14.0", optional = true, features = ["apigw_http"] }
poem = "3.1.6"
poem-lambda = { version = "5.1.2", optional = true }
poem-openapi = { version = "5.1.12", features = ["stoplight-elements", "time"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sqlx = { version = "0.8.2", features = [
    "derive",
    "migrate",
    "postgres",
    "runtime-tokio",
    "time",
    "tls-rustls-ring-native-roots",
] }
thiserror = "2.0.4"
time = { version = "0.3.41", features = [
    "formatting",
    "macros",
    "parsing",
    "serde",
] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = { version = "1.17.0", features = ["serde", "v4"] }
validator = { version = "0.20.0", features = ["derive"] }

[dev-dependencies]
poem = { version = "3.1.6", features = ["test"] }

[[test]]
name = "user"
required-features = ["testing"]
