services:
  api-rust:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    command: sleep infinity
    volumes:
      - ..:/api-rust:cached
    environment:
      TZ: ${TZ} # Timezone
      GITHUB_TOKEN: ${GITHUB_TOKEN} # Github CLI
      # See https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#example-syntax
      RUST_LOG: trace
      POSTGRES_URI: postgresql://postgres:developer@postgres:5432/postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: developer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
